name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Debugging build directory contents
        run: ls -la $GITHUB_WORKSPACE/build

      - name: Deploy to Server (Using SSH keys, recommended)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Check if the repository directory exists
            if [ -d /var/www/MB-Portfolio/.git ]; then
              echo "Repository exists, updating..."
              cd /var/www/MB-Portfolio && git fetch --all && git reset --hard origin/master
            else
              echo "Repository does not exist, cloning..."
              git clone https://github.com/cw-prime/MB-Portfolio.git /var/www/MB-Portfolio
            fi

            ## Ensure the web server user (www-data) has ownership of the deployment directory
            sudo chown -R www-data:www-data /var/www/MB-Portfolio
            sudo chmod -R 755 /var/www/MB-Portfolio

            # Safely clear existing files, preserving node_modules
            find /var/www/MB-Portfolio -mindepth 1 ! -name 'node_modules' -exec rm -rf {} +

            # Copy built files from build directory
            cp -r $GITHUB_WORKSPACE/build/* /var/www/MB-Portfolio

            # Restart Nginx to apply changes
            sudo systemctl restart nginx
